/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import java.awt.event.ActionListener;

/**
 *
 * @author Videoadicto
 */
public class VistaPrincipal extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaPrincipal.class.getName());

    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbRegistroA = new javax.swing.JTable();
        btRegistroA = new javax.swing.JButton();
        btActRegistroA = new javax.swing.JButton();
        btElimRegistroA = new javax.swing.JButton();
        btRegistroE = new javax.swing.JButton();
        btRegInc = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txId = new javax.swing.JTextField();
        txTrabBusNombre = new javax.swing.JTextField();
        txTrabBusCargo = new javax.swing.JTextField();
        btId = new javax.swing.JButton();
        btNombre = new javax.swing.JButton();
        btCargo = new javax.swing.JButton();
        btBusEvaMedica = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btBuscarTipo = new javax.swing.JButton();
        btBuscarFecha = new javax.swing.JButton();
        btBuscarTrabajador = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbIncidentes = new javax.swing.JTable();
        txDato = new javax.swing.JTextField();
        btEditarInc = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btRegSup = new javax.swing.JButton();
        btEdiSup = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbSup = new javax.swing.JTable();
        btBusNom = new javax.swing.JButton();
        btBusCargo = new javax.swing.JButton();
        txSup = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbRegistroA.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbRegistroA);

        btRegistroA.setText("Registrar");

        btActRegistroA.setText("Actualizar");

        btElimRegistroA.setText("Eliminar");

        btRegistroE.setText("Registrar Evaluacion Medica");

        btRegInc.setText("Registrar Incidente");

        jLabel1.setText("Buscar Trabajadores por Id");

        jLabel2.setText("Buscar Trabajadores por Nombre");

        jLabel3.setText("Buscar Trabajadores por Cargo");

        btId.setText("Buscar");

        btNombre.setText("Buscar");

        btCargo.setText("Buscar");

        btBusEvaMedica.setText("Buscar Evaluacion Medica");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 794, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(btRegistroA)
                                    .addGap(18, 18, 18)
                                    .addComponent(btActRegistroA))
                                .addComponent(btRegistroE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btRegInc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btElimRegistroA)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btBusEvaMedica, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txId)
                                        .addComponent(txTrabBusNombre)
                                        .addComponent(txTrabBusCargo, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btId)
                                        .addComponent(btNombre)
                                        .addComponent(btCargo)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btRegistroA)
                    .addComponent(btActRegistroA)
                    .addComponent(btElimRegistroA))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btId))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txTrabBusNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btNombre))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txTrabBusCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btCargo))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btRegistroE)
                    .addComponent(btBusEvaMedica))
                .addGap(17, 17, 17)
                .addComponent(btRegInc)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Trabajadores", jPanel1);

        btBuscarTipo.setText("Buscar Por Tipo");

        btBuscarFecha.setText("Buscar por Fecha");

        btBuscarTrabajador.setText("Buscar Por Trabajador");

        tbIncidentes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tbIncidentes);

        btEditarInc.setText("Editar Incidente");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 794, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txDato)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btBuscarTipo)
                        .addGap(18, 18, 18)
                        .addComponent(btBuscarFecha)
                        .addGap(18, 18, 18)
                        .addComponent(btBuscarTrabajador)
                        .addGap(139, 139, 139))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btEditarInc)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btBuscarTipo)
                    .addComponent(btBuscarFecha)
                    .addComponent(btBuscarTrabajador)
                    .addComponent(txDato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btEditarInc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(171, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Incidentes", jPanel3);

        btRegSup.setText("Registrar");

        btEdiSup.setText("Editar");

        tbSup.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tbSup);

        btBusNom.setText("Buscar por nombre");

        btBusCargo.setText("Buscar por cargo");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 794, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btRegSup)
                        .addGap(18, 18, 18)
                        .addComponent(btEdiSup)
                        .addGap(54, 54, 54)
                        .addComponent(txSup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(btBusNom)
                        .addGap(18, 18, 18)
                        .addComponent(btBusCargo)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btRegSup)
                    .addComponent(btEdiSup)
                    .addComponent(btBusNom)
                    .addComponent(btBusCargo)
                    .addComponent(txSup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(206, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Supervisores", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btActRegistroA;
    public javax.swing.JButton btBusCargo;
    public javax.swing.JButton btBusEvaMedica;
    public javax.swing.JButton btBusNom;
    public javax.swing.JButton btBuscarFecha;
    public javax.swing.JButton btBuscarTipo;
    public javax.swing.JButton btBuscarTrabajador;
    public javax.swing.JButton btCargo;
    public javax.swing.JButton btEdiSup;
    public javax.swing.JButton btEditarInc;
    public javax.swing.JButton btElimRegistroA;
    public javax.swing.JButton btId;
    public javax.swing.JButton btNombre;
    public javax.swing.JButton btRegInc;
    public javax.swing.JButton btRegSup;
    public javax.swing.JButton btRegistroA;
    public javax.swing.JButton btRegistroE;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    public javax.swing.JTable tbIncidentes;
    public javax.swing.JTable tbRegistroA;
    public javax.swing.JTable tbSup;
    public javax.swing.JTextField txDato;
    public javax.swing.JTextField txId;
    public javax.swing.JTextField txSup;
    public javax.swing.JTextField txTrabBusCargo;
    public javax.swing.JTextField txTrabBusNombre;
    // End of variables declaration//GEN-END:variables

    public void agregarListener(ActionListener e) {
        btRegistroA.addActionListener(e);
        btActRegistroA.addActionListener(e);
        btElimRegistroA.addActionListener(e);
        btRegistroE.addActionListener(e);
        btId.addActionListener(e);
        btNombre.addActionListener(e);
        btCargo.addActionListener(e);

        btRegSup.addActionListener(e);
        btEdiSup.addActionListener(e);

        btBuscarTipo.addActionListener(e);
        btBuscarFecha.addActionListener(e);
        btBuscarTrabajador.addActionListener(e);

       
        btBusEvaMedica.addActionListener(e);
        
        btRegInc.addActionListener(e);
        
        btEditarInc.addActionListener(e);
        
        btRegSup.addActionListener(e);
                btEdiSup.addActionListener(e);
                
                btBusNom.addActionListener(e);
                        btBusCargo.addActionListener(e);
        

    }
}
